### ISSUE TITLE
Menu and Select Screen Sounds stop playing after quitting Arcade mode.

### ISSUE THREAD

**Issue by CitrusHappy** [Windblade-GR01/Ikemen_GO#110]
Pretty self explanatory, all sounds including menu music and select screen music and their sounds stop playing when you press ESC during arcade mode.

Using a custom screenpack, let me know if you need a test build.

**Comment by K4thos** [comment]
test build is needed

**Comment by CitrusHappy** [comment]
[testbuild](https://www.mediafire.com/file/l28em3ssf9sovpq/Citrus%27_Ikemen_GO_TESTBUILD.zip/file)

**Comment by K4thos** [comment]
this is because you've left select.bgm.volume parameter not assigned, which currently means that it set to 0. The reason why you could hear it before starting the match is because you had the same music assigned to main menu and select screen (in such case ikemen continues playing previous track). I will change this behaviour to not set value at all if it's not assigned in future, but for now you can fix it yourself by assigning proper volume value to your music in screenpack def file.
