### ISSUE TITLE
Hypers do too much damage

### ISSUE THREAD

**Issue by NpMaster10** [Windblade-GR01/Ikemen_GO#149]
Agent Venom and War machine both have hyper than involve firing many bullets but it Ikemen Go it does much more damage than it should.

Link to video that shows it.
https://www.youtube.com/watch?v=8iIpmgt1JDw

Link the Characters
Agent Venom: https://scruffydragon.com/forum/index.php?action=tpmod;dl=item68
Warmachine: https://mugenguild.com/forum/topics/mvc2-war-machine-legacy-age-heroes-release-09-189922.0.html

The video is using fresh mugen 1.0 and Ikemen Go 0.94.3 builds.

**Comment by Orochikyocr** [comment]
I had this bug present when I upgraded from a previous version of Ikemen Go to 94.3 and I didnt copy common.const to my data folder, hypers does a lot of damage. Copy and replacing common.const in my data folder solved the "bug".

**Comment by K4thos** [comment]
please post a link to Agent Venom that doesn't require registering

**Comment by K4thos** [comment]
as far as I understand it's not a bug. In state 3000 of Agent Venom there are 3 states with projectiles fired on following condition:
```ini
trigger1 = time = [30,100]
```
which means the expected behavior is 210 bullets total doing 6 damage each - that's what you see in ikemen go video. The reason why there is visible, sound and damage difference between mugen and ikemen is due to mugen internal cap for the amount of projectiles that can be present on screen, causing about 2/3 projectiles to whiff in this case. Considering this character's damage is affected by PlayerProjectileMax (mugen.cfg setting) and the ikemen go does what the code actually tells it to do (unlike mugen), there is nothing to fix here.

The issue can be closed, imo.
