### ISSUE TITLE
[Feature] Dynamic BGM switch

### ISSUE THREAD

**Issue by pidgeon777** [Windblade-GR01/Ikemen_GO#35]
It would be interesting to add a way to switch the currently played BGM to another one when a certain in-game event occurs.

**Comment by pidgeon777** [comment]
I would like to add that maybe this could be implemented through a single sound file shared by the characters to save space. Thus, for example, when a certain event occurs, a specified track of that file could be activated by stopping the one being currently played (like it happens during fatalities in Mortal Kombat, for example).

**Comment by K4thos** [comment]
I've implemented this feature in this commit: https://github.com/K4thos/Ikemen-GO-Plus/commit/851566333c471d4853234d51e53ff8c8c30e5cc1

Coded in a way that should be easy to expand this functionality in future.

**Comment by pidgeon777** [comment]
This is great! In my opinion, it would be even more amazing to control the currently played BGM according to a list of defined events (for example, character intro, or power-up, or finishing moves), not only according to the player health level. To replicate what occurs, for example, during a battle in an anime, where the music changes according to the events of the fight. Do you think something like this could be achievable?

**Comment by K4thos** [comment]
since v0.95 you have 100% control which music will be played during match from within lua, nothing is hardcoded anymore. `start.f_stageMusic()` lua function can be customized, is called each frame during match and has access to all mugen triggers (so any condition can be implemented). This request is already fulfilled and should be closed, imo.
