### ISSUE TITLE
[Feature] Scoring system

### ISSUE THREAD

**Issue by Amidweiz** [Windblade-GR01/Ikemen_GO#61]
A possible implementation for this would be to have it contained within the mugen.cfg file under it's own section. It should be able to be utilized by the screenpack and the character itself (possibly with a sysvar of it's own)

>[Score]
;Enables the scoring system
enable = 1
;Enables or disables addition of score with multi hit attacks 
;such as kung fu man's crouching hard punch
multiHit = 1
;Sets whether the scoring system is counted by interegers or double values
scoreType = integer
;Sets the significant digits and the decimal place of the score counter
;integers will ignore the decimal place.
sigDig = (5,0)
;Enables or disables score rollover. Values will be saved as their true values
;in the save file
rollOver = 1
;normal score values
normalAttack = 50
normalProjectile = 50
normalThrow = 50
;special score values
specialAttack = 100
specialProjectile = 100
specialThrow = 100
;hyper score values
hyperAttack = 500
hyperProjectile = 500
hyperThrow = 500

**Comment by K4thos** [comment]
There are 2 approaches that I think we can follow to create a score system:

1. Leave it all to an external CNS file (for example add004 style common1 that already has scoring) and just get the data stored in a character variable at the end of match (there is already a function that I've implemented for this purpose - getCharVar). This way character creators (let's be honest, no one else knows CNS) could design their own score systems. There has to be a default CNS / ZSS file that comes with engine, with this functionality and it's not an easy task to create one (I don't know CNS, so don't count on me)

2. Follow Amidweiz's suggestion and do the scoring calculations in-engine, using values customizable via [Score] section of the screenpack DEF (with default values stored in a motif.lua, so that all screenpacks would be compatible by default). It would be easier to customize such system. But it also introduces hardcoded functionality (completely changing how the score is calculated would require source code edits)

Not sure what would be better - please, share your thoughts. Either way, I think add004 values could be used in either of these approaches - that system proved to work great in mugen environment, regardless of what characters are used, so instead of coming up with new values and formulas (or reverse-engineering some commercial games), we could just use add004 calculations (if author is not against it)

**Comment by K4thos** [comment]
If someone finds how scoring systems works in some commercial games please post links. Here are my findings so far:
- Capcom vs SNK: https://gamefaqs.gamespot.com/dreamcast/198680-capcom-vs-snk/faqs/9966
- Capcom vs SNK 2: https://gamefaqs.gamespot.com/arcade/562704-capcom-vs-snk-2/faqs/32441
- Street Fighter 2 (SNES): https://gamefaqs.gamespot.com/snes/588700-street-fighter-ii/faqs/25190

**Comment by K4thos** [comment]
Here are value from Street Fighter Alpha 3: 
[SFA3.txt](https://github.com/Windblade-GR01/Ikemen_GO/files/4138476/SFA3.txt)

**Comment by K4thos** [comment]
I've finished implementing in-engine support for scores that is flexible enough to allow creating both CVS2 style BP System (fractals, score affecting both attacker and opponent) as well as traditional SF style scores. Values can be assigned directly in HitDef sctrl, scores are remembered between matches, lifebar def file has now [Score] section, where we can adjust how it will be rendered in-game.

But that's stuff mostly for fullgame makers. When no value is assigned via HitDef the engine should still provide score calculation similar to above posted commercial implementations (of course fully customizable via DEF file). The static values proposed by @Amidweiz is not really a good enough solution, imo. Every single hyper move worth exactly the same score? Light kick worth the same as Hard kick? No relation between combo score and/or hit damage with the score? It definitely ain't enough considering default values will be used by majority of the engine users. Leaderboards results out of static implementation like this would not resemble scores from fighting games, regardless of what values we assign in DEF file. It needs additional factors, damage multipliers, variations, time being taken into account etc.

As mentioned above, in order to create default score values system I'd prefer to base calculations on add004 implementation. In engine I have access to everything normally available in CNS files (including HitDef, time and combo data), so it's really a matter of knowing what add004 actually does in order to implement the same thing or something similar (of course while making it fully customizable from within DEF file by exposing factors of formulas to a DEF file, like base values, multipliers etc.) Alternatively similar formulas could be designed from scratch, if someone comes up with a new system.

My CNS knowledge is not good enough to figure out how Shiyo Kakuge calculates values in add004, so a help from experienced CNS coder is needed to extract these calculations from common1.cns distributed with add004. Also if anyone knows e-mail address to Shiyo, please let me know.

Either way my Ikemen GO scores and leaderboards code is currently on hiatus, since I'm not going to push those changes to github without default customizable scoring working alongside it.

**Comment by Tabris666** [comment]
The only way to make a scoring system is using common1.cns there is no other way to get it
this is a way it was implemented in old winmugen https://mugenguild.com/forum/PHPSESSID.b8gp27p4fhosd3bdhvrh1cht14/topics/score-system-147166.0.html

**Comment by K4thos** [comment]
scoring system is already implemented since several versions. This ticket should be closed.
