### ISSUE TITLE
Quick vs team pairing issue.

### ISSUE THREAD

**Issue by FainTMako** [Windblade-GR01/Ikemen_GO#81]
Team pairing for quick vs is not predictable. For example in this fight I do
ikemen_go iceman broli homero

Result: 2v1 match  of iceman & broli vs homero
This would make me assume that if its a 3 man fight that the first team would be the first 2 players and the second team would be the last player in the arguments

now this command
ikemen_go iceman homero honey

expectation: 2v1 match of iceman & homero vs honey

result: 2v1 match iceman & honey vs homero

Thanks for fixing the bug with getting the ai selected! Its awesome watching these team fights!

**Comment by K4thos** [comment]
when it comes to characters loading, just like in mugen, player1 team consist of odd iterations (player 1, 3, (...)) and player2 team use even numbers (2, 4, (...)). So your expectation example is not correct.

While testing it, I've noticed a different bug though where changing the character team order via -p parameter didn't work (they were loaded one after another instead of respecting the parameter) – it has been fixed in the above mentioned commit.

**Comment by FainTMako** [comment]
Right but I am using the latest commit which I was thanking you for.
ikemen_go iceman broli homero

Result: 2v1 match of iceman & broli vs homero is what happens with your new commit.

I can send you those characters if you wish. It is causing unexpected results as I described. Also I think I understand the pairing system. Im newer to go and even newer to mugen so you will have to forgive me if this is previous knowledge.

I ended up fixing the issue myself. With your commit but also doing this.
	for i = 1, #t do
		selectChar(t[i].player, t[i].num + 1, t[i].pal)

I run this command which gives me repeatable results regardless of the character. Before the results would change depending on the character.

./ikemen_go -p1.ai 1 Iori-x -p2.ai 1 iceman -p3.ai 1 sandbag -p4.ai 1 goku-dbs

Produces: Goku-DBS & Iceman vs Iori-X & Sandbag. This seems to fit what you were describing as what is expected.

**Comment by K4thos** [comment]
if you're still experiencing the issue after manually applying the fix, you're probably missing some other change in quick vs code (which could had been implemented via different commit). I've tested my implementation with different configurations and always get the correct result.

> ./ikemen_go -p1.ai 1 Iori-x -p2.ai 1 iceman -p3.ai 1 sandbag -p4.ai 1 goku-dbs
> 
> Produces: Goku-DBS & Iceman vs Iori-X & Sandbag. This seems to fit what you were describing as what is expected.
the expected result of your code should be (in this order), all with AI level set to 1:
`Iori-x & Sandbag vs iceman & goku-dbs`

Either way I recommend waiting for both repositories to be compatible with one another (it will take at least several more days, maybe more) since manually applying fixes between scrips now may cause problems (there are tons of changes between lua files and some conflicts on source code level)

**Comment by Windblade-GR01** [comment]
Now that the merge is complete I think we can close this.
